CREATE TABLE [dbo].[Resume]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(100) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[City] NVARCHAR(50) NULL,
	[State] NVARCHAR(2) NULL,
	[Email] NVARCHAR(100) NULL,
	[Phone] NVARCHAR(20) NULL,
	[LinkedIn] NVARCHAR(100) NULL,
	[GitHub] NVARCHAR(100) NULL,
	[Objective] NVARCHAR(2000) NULL,
)
